name: Push to Amazon ECR

on:
  push:
    branches:
      - master   # usa master porque tu rama se llama master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar credenciales de AWS (usando los secrets que agregaste)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Step 3: Login en Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build, Tag y Push de la imagen
      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_NAME=ubuntu
          ECR_REPOSITORY=471112790575.dkr.ecr.us-east-1.amazonaws.com/clo-832-lab3
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest
